# -*- coding: utf-8 -*-
"""Classification of every finding in findings.tsv into E (実体) / V (証拠) / K (記録).
E sub-kinds: REG = repair introduced a regression or new defect
             PRE = pre-existing product defect out of scope (carried / own ECO)
             IN  = in-scope product defect or requirement gap (repaired or ruled in this ECO)
Rules used (stated for the audit trail):
 - Machinery ECOs (187 record-language gate, 191 capture harness, 192 sweep runner): the gate/harness/runner
   IS acceptance equipment, so its own behaviour is 証拠 (gates that decide acceptance), not 実体.
 - Manifest / impacted_files / ownership / consumer / independent_review.status fields -> 証拠 (by definition).
 - Test, probe, mutant-survival, missing case, evidence file missing/unreproducible/transcribed,
   evidence cited that does not show the claim, claims labelled "measured"/"pasted" with nothing behind -> 証拠.
 - Prose wrong/overstated, counts in prose, citations of wrong revision, wording between sections, code
   comments, BOM text placement, requirement text that is narrowed to match the product without changing it -> 記録.
 - A finding with two halves is classified by its lead (heading) subject.
"""
C = {}
def add(fid, layer, sub, gloss):
    C[fid] = (layer, sub, gloss)

# ---- 186 (BOM record ECO)
add("R186-F1","K","","E-BOM twin invariant misplaced too; not swept")
add("R186-F2","K","","register repair.status leftover")
add("R186-F3","V","","impacted_files omits probe2")
add("R186-F4","K","","basis overstates the ruling")
add("R186-F5","V","","probe-run.txt greps do not show claim")
add("R186-F6","K","","commit cites wrong RED revision")
add("R186-F7","V","","ECO-066 manifest verified while invariant unloadable")
add("R186b-F1","V","","closure probe counts N/A marker as gap")
# ---- 187 (record-language gate)
add("R187a-F1","K","","claim carriers omit body restatement")
add("I187a-F1","K","","same carrier omission, found independently")
add("I187a-F2","V","","gate slices wrong text silently")
add("R187a-F2","V","","probe green on narrowed gate")
add("R187a-F3","V","","selftest has no arm for refusal")
add("I187a-F3","V","","same selftest gap independently")
add("R187a-F4","V","","impacted_files lacks probe file")
add("R187a-F5","V","","premise measured before repair existed")
add("R187a-F6","K","","GREEN line wider than claim")
add("R187a-F7","K","","derivation text lacks post-ruling key")
add("R187a-F8","K","","ECO-190 records conflate questions")
add("R187a-F9","V","","gate refuses DIVERGENT when values quoted")
add("I187a-F4","V","","exempt unsliceable entry reported twice")
add("I187a-F5","V","","probe checks code/exit only")
add("I187a-F6","V","","CRLF register fails closed")
add("I187b-F2","V","","gate crashes on non-UTF-8 / no id")
add("R187b-F1","K","","probe verdict line not a carrier")
add("R187b-F2","K","","commit-message carrier undispositioned")
add("I187b-F1","V","","probe blind to empty-body skip variant")
add("R187b-F3","V","","red_observed cites old probe; no rebound RED run")
add("R187b-F4","K","","filing overstates: validate_process already blocked")
add("R187b-F5","K","","I187a-F4 carried only here")
# ---- 189 (E-BOM record ECO)
add("R189-F1","K","","strongest other unit not named")
add("R189-F2","K","","recorded reason not the measured one")
add("R189-F3","K","","E-SHELL-UI-001 sibling invariant unswept")
add("R189-F4","K","","generalisation overstates pattern")
add("R189-F5","K","","grammatical subject misdescribed")
add("R189-F6","K","","pasted owner rows cut mid-token")
# ---- 191 (capture harness)
add("I191a-F1 / R191a-F1","V","","harness holds two undeclared plans")
add("I191a-F2","V","","probe green on four wrong harnesses")
add("R191a-F2","V","","realised clause unexercised")
add("R191a-F3","V","","capture manifests carry frozen CAD numbers")
add("I191a-F3","V","","realised counts off-screen cards")
add("I191a-F4","V","","trace ignores idle offset")
add("I191a-F5","K","","declared-layout.json status fields stale")
add("R191a-F4","V","","probe dies on autocrlf; leaves worktree")
add("R191a-F5","K","","stale comments, policy comment, scripts not kept")
add("I191b-F1","V","","probe green on 31px-tolerant harness")
add("R191b-F1","V","","counterexample files are transcriptions")
add("R191b-F2","V","","disposition quotes uncommitted sweep line")
add("R191b-F3","V","","trace prints literal 0.0")
add("I191b-F2","V","","trace regex matches commented lines")
add("R191b-F4","V","","manifest status / re-run keys stale")
add("R191b-F5","K","","disposition text wrong about 052")
add("I191b-F3","K","","consumer text true only for probe cases")
add("I191b-F4","K","","residue examples incomplete")
add("I191b-F5","V","","same as R191b-F4 first half")
# ---- 192 (sweep runner)
add("I192a-F1","V","","runner build reads working-tree global.json")
add("R192a-F1","V","","working-tree runner executes inside commit")
add("I192a-F2","V","","same runner defect independently")
add("R192a-F2","K","","control plan listed as carrier wrongly")
add("R192a-F3","V","","take-out fails on path length")
add("I192a-F5","V","","same path-length dependence")
add("I192a-F3","V","","probe green on two wrong runners")
add("I192a-F4","V","","skip-worktree entries silently omitted")
add("R192a-F4","K","","other ECOs' residue still counts D6 open")
add("R192a-F5","V","","manifest omits real consumers")
add("R192a-F6","K","","hook comment now false")
add("R192a-F7","K","","form ruling has no record")
add("R192a-F8","K","","stop-condition wording differs")
add("R192a-F9","V","","machinery statements without pasted output")
add("R192a-F10","V","","probe never exercises relative GIT_INDEX_FILE")
add("R192a-F11","K","","body quotes wrong line")
add("I192a-F6","K","","control-plan stop list lacks refusal")
add("I192a-F7","K","","residue (3)/(1) inexact")
add("R192a-F12","K","","residue (3) broader than measured")
add("I192b-F1","V","","take-out uses working-tree .gitattributes")
add("R192b-F2","K","","ECO-190 key restates residue wrongly")
add("I192b-F2","V","","probe blind to untracked-file copying runner")
add("R192b-F1","V","","test vector claims case that does not exist")
add("R192b-F3","K","","residue sentence reasoned, not measured")
add("I192b-F3","V","","intent-to-add taken out as 0-byte file")
add("I192b-F4","V","","refusal leaves busy temp dir")
add("R192b-F4","K","","consumer reason cites (2) not (3)")
add("R192b-F5","K","","docstring/GREEN line say working tree")
add("R192b-F6","K","","stop text names non-commit case")
add("R192b-F7","V","","manifest review status stale")
add("R192b-F8","K","","ECO-184 residue (5) incomplete")
add("R192b-F9","K","","'same code' vs same cases")
add("R192b-F10","V","","wrong runners not committed")
add("R192b-F11","K","","filing text describes defect as current")
# ---- 193
add("R193a-F1","E","PRE","MCP save_view silently re-scopes music view global")
add("R193a-F2","E","PRE","MusicOriginView filter excludes music origin; rail wrong")
add("R193a-F3","V","","controls assert refusal in let-go state")
add("R193a-F4","E","PRE","store accepts invalid scope when service bypassed")
add("R193a-F5","K","","excluded-consumer wording inexact")
add("R193a-F6","V","","probe never checks origin kept")
add("R193a-F7","K","","run recorded as passed; title scope")
add("R193b-F1","V","","fixture moved out of user's state; gate blind")
add("R193b-F2","V","","no supervised run on committed file")
add("R193b-F3","K","","carried defects have no home")
add("R193b-F4","V","","manifest fields at filing")
# ---- 194
add("R194a-F1","V","","no frame shows condition chip for golden")
add("R194a-F2","E","PRE","long condition chip runs out of row")
add("R194a-F3","K","","tier B method misdescribed")
add("R194a-F4","V","","four files missing from impacted_files")
add("R194a-F5","V","","recorded repeatability evidence not the evidence")
add("R194a-F6","V","","centre check has no control")
add("R194a-F7","K","","product comment inaccurate")
# ---- 195
add("R195a-F1","K","","requirements YAML no longer parses")
add("R195a-F2","E","REG","#をタグに fails on music/global namesake; added by NEW-3")
add("R195a-F3","V","","NEW-2 apply repair unchecked")
add("R195a-F4","V","","four guards unqualified or redundant")
add("R195a-F5","E","IN","reader accepts pack without music-scope-v1 feature")
add("R195a-F6","K","","ruling recorded wider than implemented")
add("R195a-F7","K","","spec/REQ-092 beyond approved text")
add("R195a-F8","K","","eight vs six; undispositioned rows; manifest stale")
add("R195b-F1","K","","section 9 gives false cause")
add("R195b-F2","V","","NEW-2 apply guard not qualified alone")
add("R195b-F3","V","","case claims routes it does not run")
add("R195b-F4","K","","record script does not produce record")
add("R195b-F5","K","","eight-to-six correction does not add up")
# ---- 196
add("R196a-F1","E","PRE","save of other view moves Videos; carried node id")
add("R196a-F2","E","IN","HOME id reuse not seen as change")
add("R196a-F3","E","IN","keep clause drops dynamic value; REQ narrowed")
add("R196a-F4","V","","keep control guards root only; mutant survives")
add("R196a-F5","K","","'any other save keeps' overstates")
add("R196a-F6","V","","precondition checked for two cases only")
add("R196a-F7","V","","manifest at filing state")
add("R196b-F1","E","IN","parent id reuse not seen as change")
add("R196b-F2","E","IN","moved ancestor does not move view")
add("R196b-F3","V","","keep control blind to mutant b")
add("R196c-F1","E","REG","keep branch trusts reused id; regression")
add("R196c-F2","E","REG","same-tag-path HOME move ignored; regression")
add("R196c-F3","E","PRE","removed shown node's id reused sends elsewhere")
# ---- 197
add("R197a-F1","E","REG","snapshot read throws when first metadata NULL")
add("R197a-F2","V","","before/after result comparison not recorded")
add("R197a-F3","E","IN","REQ-063 counterexamples still true of HEAD")
add("R197a-F4","E","IN","1.0 s enforced as median; statistic unstated")
add("R197a-F5","V","","all-videos arm measures prior residue")
add("R197a-F6","V","","'on a copy' condition has no instrument")
add("R197a-F7","V","","timing boundary excludes paint")
add("R197a-F8","K","","DemoCurator sentence inaccurate")
add("R197a-F9","V","","manifest still filing's")
add("R197b-F1","V","","WithDescription false unguarded; margin as necessity")
add("R197b-F2","V","","named classes miss shell list read")
add("R197b-F3","K","","cited comparison predates repair")
add("R197b-F4","K","","spec/control plan name no statistic")
add("R197b-F5","K","","comment/manifest narrower than change")
# ---- 198
add("R198a-F1","E","IN","••• still leaves row on HOME/deep rows")
add("R198a-F2","V","","test does not check ellipsis")
add("R198a-F3","E","PRE","name column collapses under chips")
add("R198a-F4","E","PRE","placing mode overflows even short condition")
add("R198a-F5","K","","'800 wide' is really 960")
add("R198a-F6","E","PRE","line-break condition draws multi-line chip")
add("R198a-F7","K","","other part properties differ, unrecorded")
add("R198a-F8","K","","probe commit omits 1280 line")
add("R198b-F1","E","REG","new panel overflows LEFT over toggle")
add("R198b-F2","E","REG","placing mode squeezes short condition to sliver")
add("R198b-F3","K","","'short condition shows full' not every row")
add("R198b-F4","E","REG","sub-20px chip shows nothing; zero chip keeps gap")
# ---- 199
add("R199a-F1","E","IN","placement takes missing HOME id, becomes HOME")
add("R199a-F2","V","","manifest at filing; two paths unlisted")
add("R199a-F3","E","PRE","node id carried into another view")
add("R199a-F4","V","","SMOKE_UI_018 no longer tests leak")
add("R199a-F5","V","","'(measured)' with no retained measurement")
add("R199a-F6","K","","invariant filed under wrong M-BOM part")
add("R199a-F7","K","","section 6 lists done work as remaining")
add("R199b-F1","E","REG","HOME at long.MaxValue overflows next id")
add("R199b-F2","K","","cross-reference points at old part")
add("R199b-F3","K","","'holds no revision' vs 'reads none'")
# ---- 200
add("R200a-F1","E","IN","import route opens Videos at other view's node")
add("R200a-F2","K","","REQ-037 sentence wider than spec/body")
add("R200a-F3","K","","M-BOM invariant says more than code")
add("R200a-F4","K","","tests-before attributed to wrong revision")
add("R200a-F5","V","","manifest omits videos expectation consumer")
add("R200b-F1","E","REG","evaluation while other view selected loses position/sort")
add("R200b-F2","V","","manifest describes first repair")
# ---- 201
add("R201a-F1","E","IN","save of other view rewrites shown position")
add("R201a-F2","K","","M-BOM 'opening position' broader than code")
add("R201a-F3","V","","qualification covers one Tags action")
add("R201b-F1","E","PRE","deleting selected view drops shown position/sort")
add("R201b-F2","V","","RefreshClassificationAsync site unexercised; disposition wrong")
add("R201b-F3","V","","over-restricted guard survives suite")
add("R201b-F4","K","","writer sweep not recorded")
# ---- 202
add("R202a-F1","E","REG","list loses chosen sort after tag action")
add("R202a-F2","V","","no case observes list order")
add("R202a-F3","V","","'3 of 3' claim has no pasted run")
add("R202a-F4","V","","manifest execution cannot find; omits test file")
add("R202a-F5","K","","reader/writer tables slightly incomplete")
add("R202a-F6","K","","separated defects recorded only here; stale M-BOM")
add("R202b-F1","K","","folded-in behaviour has no requirement home")
add("R202b-F2","E","PRE","archive list replaced by active videos on tag change")
add("R202b-F3","V","","'nine cases RED' mutant evidence mostly shared setup")
add("R202b-F4","V","","manifest lacks folded-in scope")
# ---- 203
add("R203a-F1","E","PRE","sort change fills origin-less music scope")
add("R203a-F2","K","","'byte-identical' stronger than measured")
add("R203a-F3","V","","frame evidence no provenance; wrong pair")
add("R203a-F4","V","","filing script not retained")
add("R203a-F5","E","PRE","in-view heading redraws only on publish")
# ---- 204
add("R204a-F1","E","PRE","view over open archive keeps archive state")
add("R204a-F2","K","","body names unmeasured cause")
add("R204a-F3","V","","alone-run leg not retained")
add("R204a-F4","K","","'before' labelled wrong revision")
add("R204a-F5","V","","checks cover two of reachable routes")
add("R204a-F6","V","","rerun file has no header")
add("R204a-F7","V","","test leaves catalogues in %TEMP%")
# ---- 205
add("R205a-F1","E","PRE","scope change loses position when other view selected")
add("R205a-F2","E","PRE","return to Videos reopens root with archive flag")
add("R205a-F3","V","","checks read VM strings not Tags pane")
add("R205a-F4","V","","manifest/body at filing")
add("R205a-F5","K","","'two steps change order' loose")
# ---- 206
add("R206a-F1","E","REG","archive under music scope now empty")
add("R206a-F2","E","PRE","in-flight refresh fills scope after opening")
add("R206a-F3","V","","generation advance has no RED case")
add("R206a-F4","K","","exclusion (a) names Tags route only")
add("R206b-F1","E","IN","archive close leaves panel blank, not asking")
add("R206b-F2","E","PRE","with origin, archive close lists whole catalogue")
add("R206b-F3","E","PRE","archived video fills scope via in-flight refresh")
add("R206b-F4","K","","'collection's archive' narrower than code")
# ---- 207
add("R207a-F1","E","PRE","archived video stays selected after view opens")
add("R207a-F2","K","","body names route window does not offer")
add("R207a-F3","K","","exclusion understates Tags round trip")
# ---- 208
add("R208a-F1","V","","probe marker cannot match after repair")
add("R208a-F2","K","","inventory lists eight, ninth exists")
add("R208a-F3","K","","fixture's wider reach unrecorded")
add("R208a-F4","K","","old comment above collections")
add("R208a-F5","V","","manifest names unreached consumers")
add("R208a-F6","K","","'went first were whole' is inference")
# ---- 209
add("R209a-F1","K","","'2 of 7' should be 2 of 8")
add("R209a-F2","V","","probe feeds fixture counter when defective")
add("R209a-F3","K","","probe comment overclaims isolation")
add("R209a-F4","E","PRE","Start/Stop on two threads unsafe")
# ---- 210
add("R210a-F1","V","","M-BOM behaviours have no case; mutants survive")
add("R210a-F2","E","PRE","label under group; ••• merges with alias")
add("R210a-F3","E","REG","hidden-on-resize button keeps focus")
add("R210a-F4","E","REG","hidden buttons stay in automation tree")
add("R210a-F5","E","REG","focus border swaps parts at 2px bands")
add("R210a-F6","V","","test sliver threshold 30 vs product 60")
add("R210a-F7","K","","body/register/manifest record errors")
add("R210b-F1","K","","register error left; manifest status stale")
add("R210b-F2","V","","minimum 60 pinned only to 48")
add("R210b-F3","V","","button choice pinned only to fixture slack")
# ---- 211
add("R211a-F1","V","","three M-BOM clauses have no case")
add("R211a-F2","E","REG","hidden type/owner chips stay IsVisible")
add("R211a-F3","E","REG","label tooltip replaces keyboard-hint tooltip")
add("R211a-F4","V","","probe crashes on pre-repair view; dates wrong")
add("R211a-F5","K","","flattened rows: keyboard indent feedback unmentioned")
add("R211b-F1","V","","gap check measures box not ink")
add("R211b-F2","V","","zero-width treatment stated, unheld")
add("R211b-F3","V","","probe crash carried; section 7 miscount")

if __name__ == "__main__":
    import csv, sys, collections
    rows = [l.rstrip("\n").split("\t") for l in open("findings.tsv", encoding="utf-8") if l.strip()]
    fix = {"R196a-F3": "material"}
    ids = [r[1] for r in rows]
    missing = [i for i in ids if i not in C]
    extra = [i for i in C if i not in ids]
    assert not missing, missing
    assert not extra, extra
    out = []
    for eco, fid, sev, src in rows:
        sev = fix.get(fid, sev)
        layer, sub, gloss = C[fid]
        out.append((int(eco), fid, sev, layer, sub, gloss, src))
    with open("classified.tsv", "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f, delimiter="\t")
        w.writerow(["eco","id","severity","layer","sub","gloss","source"])
        w.writerows(out)
    # per-ECO table
    L = {"E":"実体","V":"証拠","K":"記録"}
    print("| ECO | total | 実体 | 証拠 | 記録 | 実体:REG | 実体:PRE | 実体:IN |")
    print("|---|---|---|---|---|---|---|---|")
    ecos = sorted(set(r[0] for r in out))
    T = collections.Counter()
    for e in ecos:
        rs = [r for r in out if r[0]==e]
        c = collections.Counter(r[3] for r in rs)
        s = collections.Counter(r[4] for r in rs if r[3]=="E")
        print(f"| {e} | {len(rs)} | {c['E']} | {c['V']} | {c['K']} | {s['REG']} | {s['PRE']} | {s['IN']} |")
        T.update({"n":len(rs),"E":c["E"],"V":c["V"],"K":c["K"],"REG":s["REG"],"PRE":s["PRE"],"IN":s["IN"]})
    print(f"| 合計 | {T['n']} | {T['E']} | {T['V']} | {T['K']} | {T['REG']} | {T['PRE']} | {T['IN']} |")
    print()
    print("| severity | 実体 | 証拠 | 記録 | 計 |")
    print("|---|---|---|---|---|")
    for sv in ["blocking","blocking_if_ruled","material","minor"]:
        rs = [r for r in out if r[2]==sv]
        c = collections.Counter(r[3] for r in rs)
        print(f"| {sv} | {c['E']} | {c['V']} | {c['K']} | {len(rs)} |")
    c = collections.Counter(r[3] for r in out)
    print(f"| 計 | {c['E']} | {c['V']} | {c['K']} | {len(out)} |")
    print()
    print("実体 list:")
    for r in out:
        if r[3]=="E":
            print(f"- {r[1]} [{r[2]}, {r[4]}] {r[5]}")
